"""Integration value objects, enums, and domain contracts.

Establishes strict boundaries between research estimation, strategy proposal,
risk authorization, durable intent, execution, and reconciliation.
"""

from dataclasses import dataclass, field
from decimal import Decimal
from enum import Enum, auto
import hashlib
import json
from typing import Any, Dict, List, Optional, Tuple

from gyroscope.core.numeric import assert_exact_financial_quantity, to_authoritative_decimal


class AuthorityDomain(Enum):
    """Authoritative system domains enforcing single-responsibility separation."""
    OBSERVATION = "OBSERVATION"
    STATE = "STATE"
    RESEARCH_ESTIMATION = "RESEARCH_ESTIMATION"
    EVIDENCE = "EVIDENCE"
    STRATEGY_DECISION = "STRATEGY_DECISION"
    RISK_AUTHORITY = "RISK_AUTHORITY"
    EXECUTION_INTENT = "EXECUTION_INTENT"
    BROKER_BOUNDARY = "BROKER_BOUNDARY"
    RECONCILIATION = "RECONCILIATION"
    DURABLE_STATE = "DURABLE_STATE"


class DecisionSide(Enum):
    """Trade decision side."""
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


class OrderType(Enum):
    """Supported order types."""
    MARKET = "MARKET"
    LIMIT = "LIMIT"
    STOP = "STOP"
    STOP_LIMIT = "STOP_LIMIT"


class OrderStatus(Enum):
    """Broker order lifecycle states."""
    PENDING_SUBMIT = "PENDING_SUBMIT"
    SUBMITTED = "SUBMITTED"
    ACCEPTED = "ACCEPTED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"
    UNKNOWN = "UNKNOWN"
    EXPIRED = "EXPIRED"


class RiskDecisionType(Enum):
    """Risk evaluation outcome classifications."""
    ACCEPT = "ACCEPT"
    REDUCE = "REDUCE"
    DEFER = "DEFER"
    REJECT = "REJECT"


class RecoveryState(Enum):
    """System recovery lifecycle states."""
    NORMAL = "NORMAL"
    RECOVERY_REQUIRED = "RECOVERY_REQUIRED"
    RECOVERING = "RECOVERING"
    RECONCILING = "RECONCILING"
    RECOVERY_COMPLETE = "RECOVERY_COMPLETE"
    SAFE = "SAFE"


@dataclass(frozen=True)
class SemanticObservationRef:
    """Semantic observation content identity reference (excludes envelope timestamps)."""
    semantic_id: str
    envelope_id: str
    source: str
    symbol: str
    timeframe: str
    event_timestamp_ns: int
    price: Decimal
    bid: Decimal
    ask: Decimal
    volume: Decimal

    def __post_init__(self) -> None:
        assert_exact_financial_quantity(self.price)
        assert_exact_financial_quantity(self.bid)
        assert_exact_financial_quantity(self.ask)
        assert_exact_financial_quantity(self.volume)


@dataclass(frozen=True)
class ResearchEvidencePayload:
    """Evidence payload produced by state estimation or research modules."""
    evidence_id: str
    symbol: str
    readiness_level: str
    nis_score: float
    innovation: float
    regime_label: str
    timestamp_ns: int
    provenance_node_id: str
    metrics: Dict[str, float] = field(default_factory=dict)


@dataclass(frozen=True)
class CandidateDecision:
    """Candidate strategy proposal generated by strategy logic.

    NOTE: CandidateDecision carries proposal authority ONLY. It is NOT execution authority.
    """
    decision_id: str
    opportunity_id: str
    symbol: str
    side: DecisionSide
    order_type: OrderType
    target_quantity: Decimal
    limit_price: Optional[Decimal]
    stop_price: Optional[Decimal]
    decision_timestamp_ns: int
    strategy_version: str
    provenance_node_id: str
    observation_refs: Tuple[str, ...]

    def __post_init__(self) -> None:
        assert_exact_financial_quantity(self.target_quantity)
        if self.limit_price is not None:
            assert_exact_financial_quantity(self.limit_price)
        if self.stop_price is not None:
            assert_exact_financial_quantity(self.stop_price)


@dataclass(frozen=True)
class RiskAuthorization:
    """Authorized risk evaluation result.

    Only ACCEPT or REDUCE results may produce an ExecutionIntent.
    """
    authorization_id: str
    candidate_decision_id: str
    decision_type: RiskDecisionType
    approved_quantity: Decimal
    approved_limit_price: Optional[Decimal]
    approved_stop_price: Optional[Decimal]
    max_slippage_bps: Decimal
    risk_budget_consumed: Decimal
    reason: str
    evaluated_at_ns: int
    risk_ledger_state_hash: str
    provenance_node_id: str

    def __post_init__(self) -> None:
        assert_exact_financial_quantity(self.approved_quantity)
        if self.approved_limit_price is not None:
            assert_exact_financial_quantity(self.approved_limit_price)
        if self.approved_stop_price is not None:
            assert_exact_financial_quantity(self.approved_stop_price)
        assert_exact_financial_quantity(self.max_slippage_bps)
        assert_exact_financial_quantity(self.risk_budget_consumed)

    @property
    def is_executable(self) -> bool:
        return self.decision_type in (RiskDecisionType.ACCEPT, RiskDecisionType.REDUCE) and self.approved_quantity > Decimal("0")


@dataclass(frozen=True)
class ExecutionIntent:
    """Durable authorized execution intent ready for submission to broker boundary."""
    intent_id: str
    idempotency_key: str
    request_fingerprint: str
    authorization_id: str
    symbol: str
    side: DecisionSide
    order_type: OrderType
    quantity: Decimal
    limit_price: Optional[Decimal]
    stop_price: Optional[Decimal]
    configuration_hash: str
    lineage_node_id: str
    created_at_ns: int

    def __post_init__(self) -> None:
        assert_exact_financial_quantity(self.quantity)
        if self.limit_price is not None:
            assert_exact_financial_quantity(self.limit_price)
        if self.stop_price is not None:
            assert_exact_financial_quantity(self.stop_price)


@dataclass(frozen=True)
class BrokerDeal:
    """Authoritative deal/fill execution record returned from broker."""
    deal_id: str
    order_id: str
    intent_id: str
    symbol: str
    side: DecisionSide
    fill_quantity: Decimal
    fill_price: Decimal
    fee_amount: Decimal
    fee_currency: str
    executed_at_ns: int

    def __post_init__(self) -> None:
        assert_exact_financial_quantity(self.fill_quantity)
        assert_exact_financial_quantity(self.fill_price)
        assert_exact_financial_quantity(self.fee_amount)


@dataclass(frozen=True)
class BrokerOrderRecord:
    """Current state of an order at the broker boundary."""
    broker_order_id: str
    intent_id: str
    idempotency_key: str
    symbol: str
    side: DecisionSide
    order_type: OrderType
    status: OrderStatus
    requested_quantity: Decimal
    filled_quantity: Decimal
    avg_fill_price: Optional[Decimal]
    last_update_ns: int
    raw_response_hash: str

    def __post_init__(self) -> None:
        assert_exact_financial_quantity(self.requested_quantity)
        assert_exact_financial_quantity(self.filled_quantity)
        if self.avg_fill_price is not None:
            assert_exact_financial_quantity(self.avg_fill_price)


@dataclass(frozen=True)
class ReconciliationEvidence:
    """Fresh, authoritative broker reconciliation evidence."""
    reconciliation_id: str
    broker_query_timestamp_ns: int
    is_fresh: bool
    query_quality_score: float
    matched_orders_count: int
    open_orders_count: int
    orphan_orders_count: int
    state_mismatch_detected: bool
    provenance_node_id: str
    reconciled_intent_ids: Tuple[str, ...]


@dataclass(frozen=True)
class RecoveryEvidence:
    """Recovery evidence required before entering production execution."""
    recovery_id: str
    producer_identity: str
    recovery_state: RecoveryState
    completed_at_ns: int
    reconciliation_evidence_id: str
    provenance_node_id: str
    is_valid_evidence: bool
